apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: default
  labels:
    app: nginx-dep
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-dep
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: nginx-dep-port
          containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx-service
spec:
  clusterIP: 10.106.181.154
  clusterIPs:
  - 10.106.181.154
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - nodePort: 30082
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dep
  sessionAffinity: None
