apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  clusterIP: 10.106.181.154
  clusterIPs:
  - 10.106.181.154
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: nginx-dep-port
  selector:
    app: nginx-dep
  sessionAffinity: None
