version: "2"
services:
  test-python:
    build: ./build/
    volumes:
      - "./build/app:/app"
    ports:
      - "5000:5000"
  
  test-python2:
    build: ./build2/
    volumes:
      - "./build2/app:/app"
    ports:
      - "9999:5000"