apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-dep
  template:
    metadata:
      labels:
        app: traefik-dep
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - name: traefik
        image: traefik:v2.3.6 
        ports:
        - name: web
          containerPort: 80
        - name: dashboard
          containerPort: 8080
        args:
        - --api
        - --api.dashboard=true
        - --api.insecure=true
        - --accesslog
        - --providers.kubernetescrd
        - --ping
        - --accesslog=true
        - --log=true