apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: default
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-dep
  labels:
    app: traefik-dep
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-dep
  template:
    metadata:
      labels:
        app: traefik-dep
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik-dep
          image: traefik:v2.2
          args:
            - --log.level=DEBUG
            - --api
            - --api.insecure
            - --entrypoints.web.address=:80
            - --providers.kubernetesingress
          ports:
            - name: traefik-web
              containerPort: 80
            - name: traefik-admin
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: traefik-dep
  ports:
    - protocol: TCP
      port: 8080
      name: traefik-admin
      targetPort: 8080
      nodePort: 30080
    - protocol: TCP
      port: 80
      name: traefik-web
      targetPort: 80
      nodePort: 30081
