apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
type: Opaque
data:
  user: user
  password: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep
spec:
  selector:
    matchLabels:
      app: postgres-dep
  template:
    metadata:
      labels:
        app: postgres-dep
    spec:
      containers:
      - name: postgres-dep
        image: postgres
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-auth
              key: password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-auth
              key: password
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-service
  ports:
  - port: 5432
    targetPort: 5432