apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dep
  namespace: default
  labels:
    app: grafana-dep
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana-dep
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.3.6
        imagePullPolicy: IfNotPresent
        ports:
        - name: grafana-depport
          containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: default
  labels:
    app: grafana-service
spec:
  clusterIP: 10.106.181.157
  clusterIPs:
  - 10.106.181.157
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - nodePort: 30084
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-dep
  sessionAffinity: None
