apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-dep
  namespace: default
  labels:
    app: prometheus-dep
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-dep
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.24.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: promet-depport
          containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/etc/
        args:
        - --config.file=/mnt/etc/prometheus.yaml
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
  labels:
    app: prometheus-service
spec:
  clusterIP: 10.106.181.158
  clusterIPs:
  - 10.106.181.158
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-dep
  sessionAffinity: None
